/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Study;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author java-dev
 */
public class TestFormattedText extends javax.swing.JFrame {

    /**
     * Creates new form TestFormattedText
     */
    public TestFormattedText() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTest = new javax.swing.JFormattedTextField();
        cbxTest = new javax.swing.JComboBox();
        btnTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTest.setMinimumSize(new java.awt.Dimension(6, 30));

        cbxTest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Number", "Date", "Tel" }));
        cbxTest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTestItemStateChanged(evt);
            }
        });

        btnTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTest.setText("0818751185");
        btnTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTestMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxTest, 0, 149, Short.MAX_VALUE)
                        .addComponent(txtTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTestItemStateChanged
        // TODO add your handling code here:
        if (cbxTest.getSelectedIndex() == 0) {
            txtTest.setFormatterFactory(new DefaultFormatterFactory());
            txtTest.setText("");
        } else if(cbxTest.getSelectedIndex() == 1) {
            try {
                MaskFormatter mft = new MaskFormatter("####-##-##");
                mft.setPlaceholderCharacter('_');
                txtTest.setFormatterFactory(new DefaultFormatterFactory(mft));
            } catch (ParseException ex) {
                Logger.getLogger(TestFormattedText.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(cbxTest.getSelectedIndex() == 2) {
            try {
                MaskFormatter mft = new MaskFormatter("(###)-###-####");
                mft.setPlaceholderCharacter('_');
                txtTest.setFormatterFactory(new DefaultFormatterFactory(mft));
            } catch (ParseException ex) {
                Logger.getLogger(TestFormattedText.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_cbxTestItemStateChanged

    private void btnTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTestMouseClicked
        // TODO add your handling code here:
        txtTest.setText(btnTest.getText());
    }//GEN-LAST:event_btnTestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFormattedText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFormattedText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFormattedText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFormattedText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFormattedText().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTest;
    private javax.swing.JComboBox cbxTest;
    private javax.swing.JFormattedTextField txtTest;
    // End of variables declaration//GEN-END:variables
}
