/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Study;

import java.util.Calendar;
import java.util.Locale;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import sun.util.BuddhistCalendar;

/**
 *
 * @author java-dev
 */
public class TestCbxDate extends javax.swing.JFrame {

    /**
     * Creates new form TestCbxDate
     */
    public TestCbxDate() {
        initComponents();
        setYear();
        setMonth();
        setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        cbxYear = new javax.swing.JComboBox();
        cbxMonth = new javax.swing.JComboBox();
        cbxDate = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cbxYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxYearItemStateChanged(evt);
            }
        });

        cbxMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMonthItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pnMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxDate, cbxMonth, cbxYear});

        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pnMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxDate, cbxMonth, cbxYear});

        getContentPane().add(pnMain, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxYearItemStateChanged
        // TODO add your handling code here:
        setMonth();
        setDate();
    }//GEN-LAST:event_cbxYearItemStateChanged

    private void cbxMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMonthItemStateChanged
        // TODO add your handling code here:
        setDate();
    }//GEN-LAST:event_cbxMonthItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestCbxDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestCbxDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestCbxDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestCbxDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestCbxDate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxDate;
    private javax.swing.JComboBox cbxMonth;
    private javax.swing.JComboBox cbxYear;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables

    private void setYear() {

        Calendar c = new BuddhistCalendar(new Locale("th", "TH"));

        //ปี
        int year = c.get(Calendar.YEAR);
        Vector<String> y = new Vector<>();

        for (int i = 0; i < 10; i++) {
            y.add(year + i + "");
        }
        cbxYear.setModel(new DefaultComboBoxModel(y));

    }

    private void setMonth() {

        Calendar c = new BuddhistCalendar(new Locale("th", "TH"));
        int curYear = c.get(Calendar.YEAR);
        int curMonth = c.get(Calendar.MONTH);
        String ySel = cbxYear.getSelectedItem().toString();
        String monthInYear[] = {"มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"};


        //เดือน หาปีที่ถูกเลือกมาก่อน
        Vector<String> m = new Vector<>();

        if (ySel.equals(curYear + "")) {

            for (int i = curMonth; i < 12; i++) {
                m.add(monthInYear[i]);
            }

        } else {

            for (int i = 0; i < 12; i++) {
                m.add(monthInYear[i]);
            }

        }

        cbxMonth.setModel(new DefaultComboBoxModel(m));

    }

    private void setDate() {

        Calendar c = new BuddhistCalendar(new Locale("th", "TH"));
        int curMonth = c.get(Calendar.MONTH);
        int curDate = c.get(Calendar.DATE);
        String ySel = cbxYear.getSelectedItem().toString();
        int ySelInt = Integer.parseInt(ySel) - 543;
        String monthInYear[] = {"มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"};
        String mSel = cbxMonth.getSelectedItem().toString();
        int leap = ((ySelInt % 4 == 0) && ((ySelInt % 100 != 0) || (ySelInt % 400 == 0)) ? 29 : 28);
        int dayInMonth[] = {31, leap, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        int index = 0;
        Vector<String> d = new Vector<>();
        //หาวันเดือนที่เลือกคือเดือนอะไรเพื่อตรวจสอบว่าเดือนนั้นมีกี่วัน
        for (int i = 0; i < monthInYear.length; i++) {

            if (mSel.equals(monthInYear[i])) {
                index = i;
                break;
            }

        }

        if (curMonth == index) {
            for (int i = curDate - 1; i < dayInMonth[index]; i++) {
                d.add(i + 1 + "");
            }
        } else {
            for (int i = 0; i < dayInMonth[index]; i++) {
                d.add(i + 1 + "");
            }
        }

        cbxDate.setModel(new DefaultComboBoxModel(d));

    }
}
