/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Study;

import Utility.MyComboBoxCellEditor;
import Utility.MyPasswordCellRenderer;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

/**
 *
 * @author java-dev
 */
public class TestTableEditor extends javax.swing.JFrame {

    JComboBox combo;
    
    /**
     * Creates new form Frame
     */
    public TestTableEditor() {
        initComponents();
        TableColumn column = tbTest.getColumnModel().getColumn(3);
        column.setCellRenderer(new MyPasswordCellRenderer());
        new MyComboBoxCellEditor().addComboToTable(tbTest, 1, new JComboBox());
        combo = new JComboBox(new String[] {"aaa","bbb","ccc"});
        
        combo.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                
                lbl.setText(combo.getSelectedItem().toString());
            }
        });
        tbTest.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(combo));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTest = new javax.swing.JTable();
        pn = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        psw = new javax.swing.JPasswordField();
        lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"aaaa", "aaaa", "aaaa", "a12a"},
                {"bbbb", "bbbb", "bbbb", "b34b"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTest.setRowHeight(25);
        tbTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTest);
        tbTest.getColumnModel().getColumn(0).setResizable(false);
        tbTest.getColumnModel().getColumn(1).setResizable(false);
        tbTest.getColumnModel().getColumn(2).setResizable(false);
        tbTest.getColumnModel().getColumn(3).setResizable(false);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pn.setLayout(new java.awt.GridLayout(3, 0));
        pn.add(txt);
        pn.add(psw);
        pn.add(lbl);

        getContentPane().add(pn, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTestMouseClicked
        // TODO add your handling code here:
        int rowSel = tbTest.getSelectedRow();
        
        txt.setText(tbTest.getValueAt(rowSel, 2).toString());
        psw.setText(tbTest.getValueAt(rowSel, 3).toString());
//        lbl.setText(psw.getText());
    }//GEN-LAST:event_tbTestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTableEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestTableEditor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JPanel pn;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTable tbTest;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
